name: ftg-mod-prr
on: [pull_request_review]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: "🗒️ Новый *pull-request review* от: ${{github.actor}}.\n*Репозиторий: *${{github.repository}}\n*Сообщение: *${{github.event.head_commit.message}}\n----\n*Дополнительная информация: *[по ссылке](https://github.com/${{github.repository}}/pulls)\n"